syntax = "proto3";

//Scenes

message Vector3{
	float x = 1;
	float y = 2;
	float z = 3;
}

message Transform{
	Vector3 position = 1;
	Vector3 rotation = 2;
	Vector3 scale = 3;
}

message GameObject{
	string unique_id = 1;
	string name = 2;
	Transform t = 3;
	string mesh_id = 4;
}

message WorldData{
	repeated GameObject game_objects = 1;
}

service World{
	rpc InitializeClient() returns World
}

//Meshes

message MeshRequest{
	string mesh_id = 1;
}

message Mesh{
	bytes mesh_data = 2;
}

service MeshManager{
	rpc DownloadMesh(MeshRequest) returns Mesh
}